name: Go Unit CI
on:
  push:
    branches:
    - main
  pull_request:
permissions:
  contents: read

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go: ['1.18', '1.19', '1.20', '1.21']
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@0634a2670c59f64b4a01f0f96f84700a4088b9f0 # v2.12.0
      with:
        disable-sudo: true
        egress-policy: block
        allowed-endpoints: >
          api.github.com:443
          github.com:443
          objects.githubusercontent.com:443
          proxy.golang.org:443

    - name: Checkout code
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - name: Setup Go
      uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
      with:
        go-version: ${{ matrix.go }}
        check-latest: true
    - name: Build and test
      run: "go test ./..."
    - name: Vet
      run: "go vet ./..."
